# /bin/bash

# parser.add_argument("--model_name", type=str, default="gpt-3.5-turbo")
# parser.add_argument("--model_path", type=str, default="")
# parser.add_argument("--benchmark", type=str, default="RTLLM", help="Currently, there are four valid options: RTLLM, VGen, VerilogEval, all.")
# parser.add_argument("--api_key", type=str, default="sk-")
# parser.add_argument("--base_url", type=str, default="")
# parser.add_argument("--pass_at_n", type=int, default=5)  # pass@5
# parser.add_argument("--temp_outputfile", type=str, default="temp_output/test.vvp")
# parser.add_argument("--correctness_file", type=str, default=f"correctness/correctness_file{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt")
# parser.add_argument("--gen_only", action='store_true', help="If set, only generate code without evaluation")
# parser.add_argument("--eval_only", action='store_true', help="If set, only run evaluation without generating code")
# parser.add_argument("--prompt_type", type=str, default="1", help="When the benchmark is VGen, the prompt_type should be set")
# parser.add_argument("--no_overwrite", action='store_true', help="If set, the exitsing files will not be overwritten")
# parser.add_argument("--add_module_header", action='store_true', help="The add module header to the code generated by model")

# parser.add_argument("--temperature", type=float, default=0.8)
# parser.add_argument("--N", type=int, default=5)
# parser.add_argument("--max_len", type=int, default=2048)
# parser.add_argument("--tokenizer", type=str, default='Salesforce/codet5p-220m-bimodal')
# parser.add_argument("--num_seqs_per_iter", type=int, default=1)
# parser.add_argument("--num_beams", type=int, default=4)

# If the model generate verilog code without the module header, please add "--add_module_header"
# If you want to test only without generation, please add "--eval_only"

MODEL_PATH='/data1/yliu22/lcm/rtl/github_run/saved_models/instruct_codet5p_220m_bimodal_all_complementModule_9_11_1/final_checkpoint'

python src/verilog_gen_eval.py \
--benchmark all \
--model_name codet5_200m \
--model_path $MODEL_PATH
